# -*- coding: utf-8 -*-
"""caixa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnxQ7I9NOGqY5NJMQ84B7Cwp1fAz8t8v
"""

# Nome: Dan Vasques Carvalho
# Curso: Análise e Desenvolvimento de Sistemas
# Disciplina: Projeto Integrador Extensionista – ADS 1
# Semestre Letivo: 1º Termo – 2025


print("Mercadinho BigBom")

# início do loop principal da caixa registradora, que permite que o programa reinicie automaticamente a cada compra
while True:

    lista_de_precos = [] #  lista vazia pois o programa deve receber uma quantidade indefinida de valores referentes aos preços dos produtos
    numero_produto = 1

    while True:

        preco = float(input(f"Produto {numero_produto}: R$ "))
        lista_de_precos.append(preco)
        if preco == 0:
            break
        numero_produto += 1 # passa para o próximo produto

    # Comentário para o professor:
    # Mesmo digitando, por exemplo: 5.80, o Python está exibindo 5.8 por padrão.
    # mas o valor usado no cálculo está correto e preserva os centavos.
    # Portanto, o total está matematicamente certo.

    total = sum(lista_de_precos)

    print("Total: R$ {:.2f}".format(total))

    dinheiro_recebido = float(input("Dinheiro: R$ "))

    troco = dinheiro_recebido - total

    print("Troco: R$ {:.2f}".format(troco))